//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3___Arcade
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class Gebruiker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gebruiker()
        {
            this.ScoreEndlessRunner = new HashSet<ScoreEndlessRunner>();
            this.ScoreFlappyBird = new HashSet<ScoreFlappyBird>();
            this.ScoreSnake = new HashSet<ScoreSnake>();
            this.ScoreTetris = new HashSet<ScoreTetris>();
            this.ScoreZombieShooter = new HashSet<ScoreZombieShooter>();
        }
    
        public int UserID { get; set; }
        public string Gebruikersnaam { get; set; }
        public string Paswoord { get; set; }
        public string Email { get; set; }
        public int Credits { get; set; }
        public bool Admin { get; set; }
        public bool Beheerder { get; set; }
        public int PaswoordTeller { get; set; }
        public string Avatar { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Always)]
        public virtual ICollection<ScoreEndlessRunner> ScoreEndlessRunner { get; set; }
        [JsonIgnore(Condition = JsonIgnoreCondition.Always)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreFlappyBird> ScoreFlappyBird { get; set; }
        [JsonIgnore(Condition = JsonIgnoreCondition.Always)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreSnake> ScoreSnake { get; set; }
        [JsonIgnore(Condition = JsonIgnoreCondition.Always)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreTetris> ScoreTetris { get; set; }
        [JsonIgnore(Condition = JsonIgnoreCondition.Always)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreZombieShooter> ScoreZombieShooter { get; set; }
    }
}
