//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3___Arcade
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class ScoreTetris
    {
        public int ScoreID { get; set; }
        public int Score { get; set; }
        public int FKGebruiker { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.Always)]
        public virtual Gebruiker Gebruikers { get; set; }
    }
}
